import React from 'react';
import { GeneratedContent } from '../types';

interface LivePreviewProps {
  content: GeneratedContent | null;
}

export const LivePreview: React.FC<LivePreviewProps> = ({ content }) => {
  if (!content) {
    return (
      <div className="h-full min-h-[400px] bg-slate-800 rounded-xl border border-slate-700 flex flex-col items-center justify-center p-8 text-center border-dashed">
        <div className="w-16 h-16 bg-slate-700 rounded-full flex items-center justify-center mb-4">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
        </div>
        <h3 className="text-lg font-medium text-slate-300">No Content Generated Yet</h3>
        <p className="text-slate-500 text-sm mt-2 max-w-xs">Start the bot to generate facts and images powered by Gemini.</p>
      </div>
    );
  }

  return (
    <div className="bg-slate-800 rounded-xl border border-slate-700 overflow-hidden shadow-xl h-full flex flex-col">
      <div className="p-4 border-b border-slate-700 bg-slate-900/50 flex justify-between items-center">
        <h3 className="font-bold text-white flex items-center gap-2">
          <span className="w-2 h-2 bg-red-500 rounded-full animate-pulse"></span>
          Live Preview
        </h3>
        <span className="text-xs text-slate-500 font-mono">
          {content.timestamp.toLocaleTimeString()}
        </span>
      </div>
      
      <div className="relative aspect-video w-full bg-slate-900">
        <img 
          src={`data:image/jpeg;base64,${content.imageBase64}`} 
          alt="Generated illustration" 
          className="w-full h-full object-cover"
        />
        <div className="absolute top-2 right-2 bg-black/60 backdrop-blur-sm text-white text-xs px-2 py-1 rounded border border-white/10">
          Generated by Gemini
        </div>
      </div>

      <div className="p-6 flex-1 bg-slate-800 overflow-y-auto">
        {/* Render HTML content safely for preview */}
        <div 
          className="text-slate-200 text-lg leading-relaxed font-light whitespace-pre-wrap"
          dangerouslySetInnerHTML={{ __html: content.fact }}
        />
      </div>
      
      <div className="bg-slate-900/50 p-3 text-xs text-center text-slate-500 border-t border-slate-700">
        Preview of content sent to Telegram
      </div>
    </div>
  );
};